config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :flat_find, only: [:edit, :update, :show, :destroy]

  def index
    @flats = Flat.all
  end
  
  def show
  end
  
  def edit
  end

  def update
    @flat.update(flat_params)
    if @flat.valid?
      @flat.save

      redirect_to flats_path
    else
      render :edit
    end
  end
  
  def destroy
    @flat.delete
    redirect_to flats_path
  end

  def new
    @flat = Flat.new()
  end

  def create
    flat = Flat.new(flat_params)
    if flat.valid?
      flat.save
      redirect_to flats_path
    else
      render :new
    end
  end
  
  private

  def flat_find
    @flat = Flat.find(params[:id])    
  end
  
  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.label :price_per_night, "Price per night" %>
  <%= f.text_field :price_per_night %>

  <%= f.label :number_of_guests, "Number of guests" %>
  <%= f.text_field :number_of_guests %>

  <%= f.submit "Submit" %>
<% end %>
  

app/views/flats/edit.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<div class="container">
  <h1>All our Flats (<%= @flats.count %>)</h1>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-4">
        <div class="card mt-3">
          <div class="card-header">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"><%= flat.address %></p>
            <div class="d-flex justify-content-between">
              <i class="fas fa-euro-sign"><%= flat.price_per_night %></i>
              <i class="fas fa-user-friends"><%= flat.number_of_guests %></i>
            </div>
          </div>
          <div class="card-body">
            <a href="#" class="btn text-primary"><%= link_to "More info", flat_path(flat), class: "text-primary" %></a>
            <a href="#" class="btn text-primary"><%= link_to "Edit", edit_flat_path(flat), class: "text-warning" %></a>
            <a href="#" class="btn text-primary"><%= link_to "Remove", flat_path(flat), class: "text-danger", method: :delete %></a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<div class="card">
  <img style="height: 300px; object-fit: cover;" src="https://www.qantas.com/content/travelinsider/en/explore/asia/indonesia/bali/what-not-to-do-in-bali/_jcr_content/parsysTop/hero.img.full.medium.jpg/1543366401968.jpg" alt="" class="card-img-top">
  <div class="container mt-4">

    <div class="row">
    
      <div class="col-8">
        <div class="bg-light p-4">
          <h1><%= @flat.name %></h1>
          <p><%= @flat.address %></p>
        </div>
        <br>
        <div class="bg-light p-4">
          <h3>A bit more about this flat...</h3>
          <p><strong><%= @flat.description %></strong></p>
        </div>
        <br>
        <div class="bg-light p-4">
          <h3>Details</h3>
          <i class="fas fa-euro-sign"></i>
          <strong><%= @flat.price_per_night %></strong>
          <i class="fas fa-user-friends"></i>
          <strong><%= @flat.number_of_guests %></strong>
        </div>
      </div>

      <div class="col-4">

        <div class="form-group p-2 bg-light">
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
              <div class="input-group-text">From:</div>
            </div>
            <input type="text" class="form-control" placeholder="Username">
          </div>

          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
              <div class="input-group-text">To:</div>
            </div>
            <input type="text" class="form-control" placeholder="Username">
          </div>
          <button class="btn btn-success col-12">Book</button>
        </div>

        <div class="footer">
          <div class="footer-copyright">
            Share
          </div>
          <div class="footer-links">
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-linkedin"></i></a>
          </div>
        </div> 

      </div>     
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <div class="d-flex justify-content-between container p-5">
      <%= link_to "Simple Airbnb", flats_path, class: "btn btn-outline-primary" %>
      <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary" %>
    </div>
    <%= yield %>
  </body>
</html>